### ISSUE TITLE
Sometimes addresses are 1 character short

### ISSUE THREAD

**Issue by weiglt** [Coinomi/bip39-monero#1]
Hi pal,

nice tool, but sometimes it seems to generate invalid addresses. Example BIP39 seed: post miss fiber barrel mountain change mix order moment civil skin abstract actress misery disagree curtain top chapter service fitness foster attack deny trial ,

creates following XMR seed: nocturnal useful ribbon banjo enigma lamb rarest randomly return federal ruling keep almost balding hatchet eternal impel tunnel each aimless sayings offend athlete broken impel ,

creates following invalid address: 44BS5quFo7SXZMZPpHaP8xAHFQ3CeLNMkRnPiwygz9pKikBPGoPkx4HtMuYZQbRqFcaW4UHTcBENhiEKiCJu1AZUCFSLm6

**Comment by tioann** [comment]
Bug confirmed! Very very nice finding! Much appreciated.

I have verified that BIP39 seed

        post miss fiber barrel mountain change mix order moment civil skin 
        abstract actress misery disagree curtain top chapter service fitness 
        foster attack deny trial

generates XMR seed

        nocturnal useful ribbon banjo enigma lamb rarest randomly return 
        federal ruling keep almost balding hatchet eternal impel tunnel each 
        aimless sayings offend athlete broken impel

I have also confirmed that the address shown by the BIP39 tool is

        44BS5quFo7SXZMZPpHaP8xAHFQ3CeLNMkRnPiwygz9pKikBPGoPkx4HtMuYZQbRqFcaW4UHTcBENhiEKiCJu1AZUCFSLm6

which is wrong, the correct one is

        44BS5quFo7SXZMZPpHaP8xAHFQ3CeLNMkRnPiwygz9pKikBPGoPkx4H1tMuYZQbRqFcaW4UHTcBENhiEKiCJu1AZUCFSLm6

This is apparently a bug in base58 code, will fix.

**Comment by weiglt** [comment]
Cool! For me chances to generate the bug are approx. 10%, subaddresses are also affected.

**Comment by tioann** [comment]
Fixed in https://github.com/Coinomi/bip39-monero/commit/27009931954442db03e7419cc9bfa8e69f2ce8ec
